name: Build
on:
  push:
    branches: [master]
jobs:
    # Job neve tetszőlegesen választható
    build:
        name: Build binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.13'
                cache: 'pip'
            - name: Install Dependencies
              run: pip install -c constraints.txt .[dev]
            - name: Static Analysis
              run: pre-commit --all--files
            - name: Unit Tests
              run: pytest -v test/unit
            - name: Create Docker Image
              run: docker build -t employee-python .
              #End i think :D :D

